In [1]:
import numpy as np
import pandas as pd
import pickle

filename = 'heart.csv'

In [14]:
df = pd.read_csv(filename)
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [10]:
data = np.loadtxt(filename, delimiter=',', skiprows=1)
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [12]:
data = np.genfromtxt(filename, delimiter=',', dtype=None, names=True, encoding='utf-8-sig')
print (data)
print (data.dtype)

[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 3, 150, 283, 1, 0, 162, 0, 1. , 2, 0, 2, 1)
 (50, 0, 2, 120, 219, 0, 1, 158, 0, 1.6, 1, 0, 2, 1)
 (58, 0, 2, 120, 340, 0, 1, 172, 0, 0. , 2, 0, 2, 1)
 (66, 0, 3, 150, 226, 0, 1, 114, 0, 2.6, 0, 0, 2, 1)
 (43, 1, 0, 150, 247, 0, 1, 171, 0, 1.5, 2, 0,

In [13]:
'''
pickle
'''
df  = pd.read_pickle('heart.pkl')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

## Lesson 9 - Pandas Vs Numpy   tinyurl.com/d_

In [15]:
df = pd.read_csv("heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [16]:
data = df.to_numpy()
data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [17]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [18]:
print(data.dtype, data) #converts to floats

float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [19]:
data[0,0] = 100
df.head()  #original df hasn't changed

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [23]:
df2 = df[["age", "sex", "cp"]]
data2 = df2.to_numpy()
data2[0,0] = 100
df2    

#numpy doesn't make a copy because selected columns are all ints
#need to be careful because the to_numpy() function sometimes will copy and 
#sometimes not.

#to force a copy, always call the copy method:
data3 = df2.to_numpy().copy()
data3[0,0] = 500
df2 # unchanged

age  sex  cp
0    100    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [26]:
df.age.to_numpy()[0] = 700
df.head() # original data is changed

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0  700    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [29]:
#calcuate the mean of the age column
print (df['age'].mean(), df['age'].to_numpy().mean())   

56.46864686468647 56.46864686468647


## Creating DataFrames

In [38]:
data = np.random.random(size=(5,3))
print(data)
df = pd.DataFrame(data=data, columns=["A", "B", "C"])
df

[[0.92033782 0.6314792  0.30693711]
 [0.43533631 0.62334003 0.87779255]
 [0.66946121 0.64203026 0.67507225]
 [0.87594343 0.35540791 0.84481978]
 [0.69468299 0.734584   0.26449766]]


A         B         C
0  0.920338  0.631479  0.306937
1  0.435336  0.623340  0.877793
2  0.669461  0.642030  0.675072
3  0.875943  0.355408  0.844820
4  0.694683  0.734584  0.264498

In [39]:
# passing in columns as dictionaries
df = pd.DataFrame(data={"A": [1,2,3],
                        "B": ["Sam", "Alex", "John-O"]})
df

A       B
0  1     Sam
1  2    Alex
2  3  John-O

In [42]:
#define datatype and passing in data as an array of tuples
dtype = [("A", np.int),("B", (np.str, 20))]
data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype=dtype)
print(data)
print(data.dtype)
df = pd.DataFrame(data)
df

[(1, 'Sam') (2, 'Alex') (3, 'John')]
[('A', '<i8'), ('B', '<U20')]


A     B
0  1   Sam
1  2  Alex
2  3  John

In [43]:
#passing in rows as dictionaries
data = [{"A":1, "B": "Sam"}, {"A":2, "B": "Alex"}, {"A":3, "B": "John-o"}]
df = pd.DataFrame(data)
df

A       B
0  1     Sam
1  2    Alex
2  3  John-o

## Saving and Serializing

In [45]:
df = pd.DataFrame(np.random.random(size=(1000000, 4)), columns=["A", "B", "C", "D"])
df.head()

A         B         C         D
0  0.512849  0.405595  0.728600  0.697795
1  0.130969  0.315471  0.057327  0.225563
2  0.066131  0.909234  0.316052  0.720681
3  0.541292  0.178159  0.374801  0.635511
4  0.080042  0.175689  0.528370  0.778214

In [52]:
# df.to_csv("save.csv", index=False, float_format="%0.2f")
# df.to_pickle("save.pkl")
# df.to_json("save.json")

In [2]:
df = pd.read_csv("astronauts.csv")
df.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired   3/3/1946     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired  5/20/1951  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired  1/20/1930  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                              STS 51-F (Challenger)        NaN           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaN           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaN           NaN  
4                               Gemini 12, Apollo 11        NaN           NaN

In [4]:
df.to_csv("save.csv", index=False, float_format="%0.4f")

In [6]:
%ll

total 171112
-rw-r--r--@ 1 matt  staff     38611 Mar 17 14:22 1_Loading.ipynb
-rw-r--r--@ 1 matt  staff     32411 Mar 17 14:25 2_NumpyVPandas.ipynb
-rw-r--r--@ 1 matt  staff      9306 Mar 17 14:26 3_CreatingDataFrames.ipynb
-rw-r--r--@ 1 matt  staff     18594 Mar 17 14:27 4_SavingAndSerialising.ipynb
-rw-r--r--@ 1 matt  staff     29596 Mar 17 14:30 5_Inspecting.ipynb
-rw-r--r--  1 matt  staff     82767 Apr 26 12:59 Section 2.ipynb
-rw-r--r--@ 1 matt  staff     81593 Sep 20  2019 astronauts.csv
-rw-r--r--@ 1 matt  staff     11328 Oct  1  2019 heart.csv
-rw-r--r--@ 1 matt  staff     35216 Jan 18 13:19 heart.pkl
-rw-r--r--@ 1 matt  staff     45851 Apr 26 11:39 original.zip
-rw-r--r--  1 matt  staff  87110632 Apr 26 12:48 python
-rw-r--r--  1 matt  staff     86672 Apr 26 12:58 save.csv


## Inspecting Data Frames
* head
* tail
* sample
* info
* describe

In [8]:
df = pd.read_csv("astronauts.csv")
df.head(2)


Name    Year  Group   Status Birth Date    Birth Place Gender  \
0  Joseph M. Acaba  2004.0   19.0   Active  5/17/1967  Inglewood, CA   Male   
1   Loren W. Acton     NaN    NaN  Retired   3/7/1936   Lewiston, MT   Male   

                                          Alma Mater  Undergraduate Major  \
0  University of California-Santa Barbara; Univer...              Geology   
1   Montana State University; University of Colorado  Engineering Physics   

  Graduate Major Military Rank Military Branch  Space Flights  \
0        Geology           NaN             NaN              2   
1  Solar Physics           NaN             NaN              1   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   

                                 Missions Death Date Death Mission  
0  STS-119 (Discovery), ISS-31/32 (Soyuz)        NaN           NaN  
1                   STS 51-F (Challenger)        NaN           NaN

In [9]:
df.tail(6)


Name    Year  Group   Status Birth Date  \
351     Peter J. K. Wisoff  1990.0   13.0  Retired  8/16/1958   
352          David A. Wolf  1990.0   13.0  Retired  8/23/1956   
353  Neil W. Woodward III   1998.0   17.0  Retired  7/26/1962   
354       Alfred M. Worden  1966.0    5.0  Retired   2/7/1932   
355          John W. Young  1962.0    2.0  Retired  9/24/1930   
356        George D. Zamka  1998.0   17.0  Retired  6/29/1962   

           Birth Place Gender  \
351        Norfolk, VA   Male   
352   Indianapolis, IN   Male   
353        Chicago, IL   Male   
354        Jackson, MI   Male   
355  San Francisco, CA   Male   
356    Jersey City, NJ   Male   

                                            Alma Mater  \
351        University of Virginia; Stanford University   
352              Purdue University; Indiana University   
353  MIT; University of Texas-Austin; George Washin...   
354        US Military Academy; University of Michigan   
355                    Georgia Institute of Technology   
356  US Naval Academy; Florida Institute of Technology   

          Undergraduate Major                            Graduate Major  \
351                   Physics                           Applied Physics   
352    Electrical Engineering                                  Medicine   
353                   Physics              Physics; Business Management   
354          Military Science  Aeronautical & Astronautical Engineering   
355  Aeronautical Engineering                                       NaN   
356               Mathematics                    Engineering Management   

    Military Rank            Military Branch  Space Flights  \
351           NaN                        NaN              4   
352           NaN                        NaN              3   
353     Commander                    US Navy              0   
354       Colonel     US Air Force (Retired)              1   
355       Captain          US Navy (Retired)              6   
356       Colonel  US Marine Corps (Retired)              2   

     Space Flight (hr)  Space Walks  Space Walks (hr)  \
351               1064            3              20.0   
352               4044            7              41.0   
353                  0            0               0.0   
354                295            1               0.5   
355                835            3              20.0   
356                692            0               0.0   

                                              Missions Death Date  \
351  STS-57 (Endeavor), STS-68 (Endeavor), STS-81 (...        NaN   
352  STS-58 (Columbia). STS-86/89 (Atlantis/Endeavo...        NaN   
353                                                NaN        NaN   
354                                          Apollo 15        NaN   
355  Gemini 3, Gemini 10, Apollo 10, Apollo 16, STS...        NaN   
356            STS-120 (Discovery), STS-130 (Endeavor)        NaN   

    Death Mission  
351           NaN  
352           NaN  
353           NaN  
354           NaN  
355           NaN  
356           NaN

In [29]:
df.sample(6, replace=True) 
# random selection.  Replace param will resample rows if set to True

Name    Year  Group      Status  Birth Date  \
338         Paul J. Weitz  1966.0    5.0     Retired   6/25/1932   
153        Susan J. Helms  1990.0   13.0     Retired   2/26/1958   
230      Leland D. Melvin  1998.0   17.0  Management   2/15/1964   
134      Dominic L. Gorie  1995.0   15.0     Retired    5/2/1957   
194  Byron K. Lichtenberg     NaN    NaN     Retired   2/19/1948   
234     Barbara R. Morgan  1998.0   17.0     Retired  11/28/1951   

          Birth Place  Gender  \
338          Erie, PA    Male   
153     Charlotte, NC  Female   
230     Lynchburg, VA    Male   
134  Lake Charles, LA    Male   
194   Stroudsburg, PA    Male   
234        Fresno, CA  Female   

                                            Alma Mater  \
338  Pennsylvania State University; US Naval Postgr...   
153          US Air Force Academy; Stanford University   
230     University of Richmond; University of Virginia   
134          US Naval Academy; University of Tennessee   
194                              Brown University; MIT   
234                                Stanford University   

          Undergraduate Major                                  Graduate Major  \
338  Aeronautical Engineering                        Aeronautical Engineering   
153  Aeronautical Engineering                      Aeronautics & Astronautics   
230                 Chemistry                   Materials Science Engineering   
134         Ocean Engineering                                Aviation Systems   
194     Aerospace Engineering  Mechanical Engineering; Biomedical Engineering   
234             Human Biology                                             NaN   

          Military Rank    Military Branch  Space Flights  Space Flight (hr)  \
338             Captain  US Navy (Retired)              2                793   
153  Lieutenant General       US Air Force              5               5063   
230                 NaN                NaN              2                565   
134             Captain  US Navy (Retired)              4               1167   
194                 NaN                NaN              2                461   
234                 NaN                NaN              1                305   

     Space Walks  Space Walks (hr)  \
338            1               2.0   
153            1               9.0   
230            0               0.0   
134            0               0.0   
194            0               0.0   
234            0               0.0   

                                              Missions Death Date  \
338                       Skylab 2, STS-6 (Challenger)        NaN   
153  STS-54 (Endeavor), STS-64 (Discovery), STS-78 ...        NaN   
230             STS-122 (Atlantis), STS-129 (Atlantis)        NaN   
134  STS-91 (Discovery), STS-99 (Endeavor), STS-123...        NaN   
194                STS-9 (Columbia), STS-45 (Atlantis)        NaN   
234                                 STS-118 (Endeavor)        NaN   

    Death Mission  
338           NaN  
153           NaN  
230           NaN  
134           NaN  
194           NaN  
234           NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 357 non-null    object 
 1   Year                 330 non-null    float64
 2   Group                330 non-null    float64
 3   Status               357 non-null    object 
 4   Birth Date           357 non-null    object 
 5   Birth Place          357 non-null    object 
 6   Gender               357 non-null    object 
 7   Alma Mater           356 non-null    object 
 8   Undergraduate Major  335 non-null    object 
 9   Graduate Major       298 non-null    object 
 10  Military Rank        207 non-null    object 
 11  Military Branch      211 non-null    object 
 12  Space Flights        357 non-null    int64  
 13  Space Flight (hr)    357 non-null    int64  
 14  Space Walks          357 non-null    int64  
 15  Space Walks (hr)     357 non-null    flo

In [31]:
df.describe()

Year       Group  Space Flights  Space Flight (hr)  Space Walks  \
count   330.000000  330.000000     357.000000         357.000000   357.000000   
mean   1985.106061   11.409091       2.364146        1249.266106     1.246499   
std      13.216147    5.149962       1.428700        1896.759857     2.056989   
min    1959.000000    1.000000       0.000000           0.000000     0.000000   
25%    1978.000000    8.000000       1.000000         289.000000     0.000000   
50%    1987.000000   12.000000       2.000000         590.000000     0.000000   
75%    1996.000000   16.000000       3.000000        1045.000000     2.000000   
max    2009.000000   20.000000       7.000000       12818.000000    10.000000   

       Space Walks (hr)  
count        357.000000  
mean           7.707283  
std           13.367973  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           12.000000  
max           67.000000

In [33]:
df.shape

(357, 19)

In [35]:
df.corr()

Year     Group  Space Flights  Space Flight (hr)  \
Year               1.000000  0.980934       0.036420           0.331386   
Group              0.980934  1.000000      -0.011386           0.325683   
Space Flights      0.036420 -0.011386       1.000000           0.325233   
Space Flight (hr)  0.331386  0.325683       0.325233           1.000000   
Space Walks        0.210073  0.217891       0.257073           0.472796   
Space Walks (hr)   0.253502  0.261384       0.258642           0.454408   

                   Space Walks  Space Walks (hr)  
Year                  0.210073          0.253502  
Group                 0.217891          0.261384  
Space Flights         0.257073          0.258642  
Space Flight (hr)     0.472796          0.454408  
Space Walks           1.000000          0.985755  
Space Walks (hr)      0.985755          1.000000

In [46]:
#Counts number of distinct values
df["Group"].value_counts()

16.0    35
8.0     35
17.0    25
13.0    22
5.0     19
14.0    19
9.0     19
15.0    19
10.0    17
18.0    17
12.0    15
3.0     15
11.0    13
19.0    11
6.0     11
2.0      9
20.0     9
1.0      7
7.0      7
4.0      6
Name: Group, dtype: int64

In [45]:
#max, min values from every column
df.max()



Name                 Yvonne D. Cagle
Year                            2009
Group                             20
Status                       Retired
Birth Date                  9/9/1952
Birth Place              Yonkers, NY
Gender                          Male
Space Flights                      7
Space Flight (hr)              12818
Space Walks                       10
Space Walks (hr)                  67
dtype: object

In [44]:
df.min()

Name                 Alan B. Shepard Jr. 
Year                                 1959
Group                                   1
Status                             Active
Birth Date                      1/14/1943
Birth Place                  Abington, PA
Gender                             Female
Space Flights                           0
Space Flight (hr)                       0
Space Walks                             0
Space Walks (hr)                        0
dtype: object